version: '3.8'
services:
  stats-server:
    build: ./stats-server/stats-server-src
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats

  stats-db:
    image: postgres:14.6-alpine3.16
    container_name: stats-db
    ports:
      - "6431:5432"
    environment:
      - POSTGRES_DB=stats
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test

  ewm-service:
    build: ./ewm-service
    container_name: ewm-service
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - STATS_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm

  ewm-db:
    image: postgres:14.6-alpine3.16
    container_name: ewm-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
